"""Trading Strategies and Gene Pool."""

from .base import (
    SignalType,
    SignalStrength,
    TradingSignal,
    StrategyConfig,
    BaseStrategy,
    StrategyGenome,
)
from .gene_pool import (
    STRATEGY_GENE_POOL,
    create_strategy,
    get_available_strategies,
    get_default_parameters,
    MovingAverageCrossover,
    TripleMovingAverage,
    TrendFollowingBreakout,
    ADXTrend,
    ParabolicSAR,
    BollingerBandMeanReversion,
    RSIMeanReversion,
    StochasticMeanReversion,
    MACDMomentum,
    ROCMomentum,
    DualMomentum,
    ATRBreakout,
    VolatilityContraction,
    MultiIndicatorConfirmation,
)

__all__ = [
    "SignalType",
    "SignalStrength",
    "TradingSignal",
    "StrategyConfig",
    "BaseStrategy",
    "StrategyGenome",
    "STRATEGY_GENE_POOL",
    "create_strategy",
    "get_available_strategies",
    "get_default_parameters",
    "MovingAverageCrossover",
    "TripleMovingAverage",
    "TrendFollowingBreakout",
    "ADXTrend",
    "ParabolicSAR",
    "BollingerBandMeanReversion",
    "RSIMeanReversion",
    "StochasticMeanReversion",
    "MACDMomentum",
    "ROCMomentum",
    "DualMomentum",
    "ATRBreakout",
    "VolatilityContraction",
    "MultiIndicatorConfirmation",
]
