"""
Base Strategy Classes and Trading Signal Definitions

All strategies inherit from BaseStrategy and implement generate_signals().
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple
from uuid import uuid4
import numpy as np


class SignalType(Enum):
    """Type of trading signal."""
    LONG_ENTRY = "long_entry"
    LONG_EXIT = "long_exit"
    SHORT_ENTRY = "short_entry"
    SHORT_EXIT = "short_exit"


class SignalStrength(Enum):
    """Strength of the signal."""
    WEAK = 1
    MODERATE = 2
    STRONG = 3
    VERY_STRONG = 4


@dataclass
class TradingSignal:
    """A trading signal generated by a strategy."""
    signal_id: str
    timestamp: datetime
    symbol: str
    signal_type: SignalType
    side: str  # 'buy' or 'sell'
    quantity: float
    price: Optional[float] = None  # Limit price, None for market
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    strength: SignalStrength = SignalStrength.MODERATE
    confidence: float = 0.5  # 0-1
    reasoning: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    @classmethod
    def buy(
        cls,
        symbol: str,
        quantity: float,
        timestamp: datetime,
        **kwargs
    ) -> 'TradingSignal':
        return cls(
            signal_id=str(uuid4()),
            timestamp=timestamp,
            symbol=symbol,
            signal_type=SignalType.LONG_ENTRY,
            side='buy',
            quantity=quantity,
            **kwargs
        )

    @classmethod
    def sell(
        cls,
        symbol: str,
        quantity: float,
        timestamp: datetime,
        **kwargs
    ) -> 'TradingSignal':
        return cls(
            signal_id=str(uuid4()),
            timestamp=timestamp,
            symbol=symbol,
            signal_type=SignalType.LONG_EXIT,
            side='sell',
            quantity=quantity,
            **kwargs
        )

    @classmethod
    def short(
        cls,
        symbol: str,
        quantity: float,
        timestamp: datetime,
        **kwargs
    ) -> 'TradingSignal':
        return cls(
            signal_id=str(uuid4()),
            timestamp=timestamp,
            symbol=symbol,
            signal_type=SignalType.SHORT_ENTRY,
            side='sell',
            quantity=quantity,
            **kwargs
        )

    @classmethod
    def cover(
        cls,
        symbol: str,
        quantity: float,
        timestamp: datetime,
        **kwargs
    ) -> 'TradingSignal':
        return cls(
            signal_id=str(uuid4()),
            timestamp=timestamp,
            symbol=symbol,
            signal_type=SignalType.SHORT_EXIT,
            side='buy',
            quantity=quantity,
            **kwargs
        )


@dataclass
class StrategyConfig:
    """Base configuration for strategies."""
    strategy_id: str
    name: str
    version: str = "1.0.0"
    symbols: List[str] = field(default_factory=list)
    parameters: Dict[str, Any] = field(default_factory=dict)
    risk_per_trade: float = 0.02  # 2% risk per trade
    max_positions: int = 10
    enable_shorting: bool = True


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    All competitive agents generate strategies that inherit from this class.
    The generate_signals() method is what gets evolved and optimized.
    """

    def __init__(self, config: StrategyConfig):
        self.config = config
        self.strategy_id = config.strategy_id
        self.name = config.name
        self.parameters = config.parameters
        self._history: Dict[str, List[float]] = {}
        self._indicators: Dict[str, Dict[str, float]] = {}

    @abstractmethod
    def initialize(self) -> None:
        """Initialize strategy state. Called before backtest."""
        pass

    @abstractmethod
    def generate_signals(
        self,
        market_data: Dict[str, Any],
        portfolio: Any,
        timestamp: datetime
    ) -> List[TradingSignal]:
        """
        Generate trading signals based on current market state.

        Args:
            market_data: Current market data snapshot {symbol: MarketData}
            portfolio: Current portfolio state
            timestamp: Current timestamp

        Returns:
            List of trading signals to execute
        """
        pass

    def update_history(self, symbol: str, price: float, max_length: int = 500):
        """Update price history for a symbol."""
        if symbol not in self._history:
            self._history[symbol] = []
        self._history[symbol].append(price)
        if len(self._history[symbol]) > max_length:
            self._history[symbol] = self._history[symbol][-max_length:]

    def get_history(self, symbol: str) -> List[float]:
        """Get price history for a symbol."""
        return self._history.get(symbol, [])

    def calculate_position_size(
        self,
        portfolio_value: float,
        entry_price: float,
        stop_loss: float
    ) -> float:
        """Calculate position size based on risk management."""
        if stop_loss == 0 or entry_price == stop_loss:
            return 0

        risk_amount = portfolio_value * self.config.risk_per_trade
        risk_per_share = abs(entry_price - stop_loss)
        return risk_amount / risk_per_share

    # ===== Technical Indicator Calculations =====

    def sma(self, prices: List[float], period: int) -> Optional[float]:
        """Simple Moving Average."""
        if len(prices) < period:
            return None
        return np.mean(prices[-period:])

    def ema(self, prices: List[float], period: int) -> Optional[float]:
        """Exponential Moving Average."""
        if len(prices) < period:
            return None

        multiplier = 2 / (period + 1)
        ema_val = prices[0]
        for price in prices[1:]:
            ema_val = (price * multiplier) + (ema_val * (1 - multiplier))
        return ema_val

    def rsi(self, prices: List[float], period: int = 14) -> Optional[float]:
        """Relative Strength Index."""
        if len(prices) < period + 1:
            return None

        deltas = np.diff(prices[-(period + 1):])
        gains = np.where(deltas > 0, deltas, 0)
        losses = np.where(deltas < 0, -deltas, 0)

        avg_gain = np.mean(gains)
        avg_loss = np.mean(losses)

        if avg_loss == 0:
            return 100

        rs = avg_gain / avg_loss
        return 100 - (100 / (1 + rs))

    def macd(
        self,
        prices: List[float],
        fast: int = 12,
        slow: int = 26,
        signal: int = 9
    ) -> Tuple[Optional[float], Optional[float], Optional[float]]:
        """MACD indicator."""
        if len(prices) < slow + signal:
            return None, None, None

        fast_ema = self.ema(prices, fast)
        slow_ema = self.ema(prices, slow)

        if fast_ema is None or slow_ema is None:
            return None, None, None

        macd_line = fast_ema - slow_ema

        # Calculate signal line (EMA of MACD)
        # Simplified - would need MACD history for proper calculation
        signal_line = macd_line * 0.9  # Approximation

        histogram = macd_line - signal_line

        return macd_line, signal_line, histogram

    def bollinger_bands(
        self,
        prices: List[float],
        period: int = 20,
        std_dev: float = 2.0
    ) -> Tuple[Optional[float], Optional[float], Optional[float]]:
        """Bollinger Bands."""
        if len(prices) < period:
            return None, None, None

        sma_val = np.mean(prices[-period:])
        std = np.std(prices[-period:])

        upper = sma_val + (std * std_dev)
        lower = sma_val - (std * std_dev)

        return upper, sma_val, lower

    def atr(
        self,
        highs: List[float],
        lows: List[float],
        closes: List[float],
        period: int = 14
    ) -> Optional[float]:
        """Average True Range."""
        if len(closes) < period + 1:
            return None

        true_ranges = []
        for i in range(1, min(len(closes), period + 1)):
            high_low = highs[-(period + 1 - i)] - lows[-(period + 1 - i)]
            high_close = abs(highs[-(period + 1 - i)] - closes[-(period + 2 - i)])
            low_close = abs(lows[-(period + 1 - i)] - closes[-(period + 2 - i)])
            true_ranges.append(max(high_low, high_close, low_close))

        return np.mean(true_ranges)

    def stochastic(
        self,
        highs: List[float],
        lows: List[float],
        closes: List[float],
        k_period: int = 14,
        d_period: int = 3
    ) -> Tuple[Optional[float], Optional[float]]:
        """Stochastic Oscillator."""
        if len(closes) < k_period:
            return None, None

        highest_high = max(highs[-k_period:])
        lowest_low = min(lows[-k_period:])

        if highest_high == lowest_low:
            return 50, 50

        k = 100 * (closes[-1] - lowest_low) / (highest_high - lowest_low)
        d = k  # Simplified - would need K history for proper %D

        return k, d

    def momentum(self, prices: List[float], period: int = 10) -> Optional[float]:
        """Price momentum."""
        if len(prices) < period + 1:
            return None
        return prices[-1] - prices[-(period + 1)]

    def rate_of_change(self, prices: List[float], period: int = 10) -> Optional[float]:
        """Rate of Change."""
        if len(prices) < period + 1:
            return None
        return ((prices[-1] - prices[-(period + 1)]) / prices[-(period + 1)]) * 100

    def obv(self, closes: List[float], volumes: List[int]) -> Optional[float]:
        """On-Balance Volume."""
        if len(closes) < 2 or len(volumes) < 2:
            return None

        obv_val = 0
        for i in range(1, len(closes)):
            if closes[i] > closes[i - 1]:
                obv_val += volumes[i]
            elif closes[i] < closes[i - 1]:
                obv_val -= volumes[i]

        return obv_val

    def vwap(
        self,
        highs: List[float],
        lows: List[float],
        closes: List[float],
        volumes: List[int]
    ) -> Optional[float]:
        """Volume Weighted Average Price."""
        if not closes or not volumes:
            return None

        typical_prices = [(h + l + c) / 3 for h, l, c in zip(highs, lows, closes)]
        cumulative_tp_vol = sum(tp * v for tp, v in zip(typical_prices, volumes))
        cumulative_vol = sum(volumes)

        return cumulative_tp_vol / cumulative_vol if cumulative_vol > 0 else None

    def crosses_above(self, fast: List[float], slow: List[float]) -> bool:
        """Check if fast crossed above slow."""
        if len(fast) < 2 or len(slow) < 2:
            return False
        return fast[-2] <= slow[-2] and fast[-1] > slow[-1]

    def crosses_below(self, fast: List[float], slow: List[float]) -> bool:
        """Check if fast crossed below slow."""
        if len(fast) < 2 or len(slow) < 2:
            return False
        return fast[-2] >= slow[-2] and fast[-1] < slow[-1]


class StrategyGenome:
    """
    Represents the genetic encoding of a strategy.

    Used by the genetic programming system to evolve strategies.
    """

    def __init__(self):
        self.genes: Dict[str, Any] = {}

    def encode(self, strategy: BaseStrategy) -> 'StrategyGenome':
        """Encode a strategy into a genome."""
        self.genes = {
            'strategy_type': type(strategy).__name__,
            'parameters': strategy.parameters.copy(),
            'config': {
                'risk_per_trade': strategy.config.risk_per_trade,
                'max_positions': strategy.config.max_positions,
                'enable_shorting': strategy.config.enable_shorting,
            }
        }
        return self

    def mutate(self, mutation_rate: float = 0.1) -> 'StrategyGenome':
        """Mutate the genome."""
        new_genome = StrategyGenome()
        new_genome.genes = self.genes.copy()

        for param, value in new_genome.genes.get('parameters', {}).items():
            if np.random.random() < mutation_rate:
                if isinstance(value, (int, float)):
                    # Mutate numeric parameters by ±20%
                    new_genome.genes['parameters'][param] = value * (1 + np.random.uniform(-0.2, 0.2))
                elif isinstance(value, bool):
                    new_genome.genes['parameters'][param] = not value

        return new_genome

    def crossover(self, other: 'StrategyGenome') -> 'StrategyGenome':
        """Crossover with another genome."""
        child = StrategyGenome()
        child.genes = {}

        # Mix parameters from both parents
        all_params = set(self.genes.get('parameters', {}).keys()) | set(other.genes.get('parameters', {}).keys())

        child.genes['parameters'] = {}
        for param in all_params:
            if np.random.random() < 0.5 and param in self.genes.get('parameters', {}):
                child.genes['parameters'][param] = self.genes['parameters'][param]
            elif param in other.genes.get('parameters', {}):
                child.genes['parameters'][param] = other.genes['parameters'][param]

        # Inherit strategy type from fitter parent (assume self is fitter)
        child.genes['strategy_type'] = self.genes.get('strategy_type', other.genes.get('strategy_type'))
        child.genes['config'] = self.genes.get('config', other.genes.get('config', {}))

        return child

    def to_dict(self) -> Dict[str, Any]:
        return self.genes.copy()

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'StrategyGenome':
        genome = cls()
        genome.genes = data.copy()
        return genome
